// TEMPORARY DATA

export let role = "member";

// PASTORS DATA (formerly TEACHERS)
export const pastorsData = [
  {
    id: 1,
    pastorId: "PST001",
    name: "John Doe",
    email: "john.doe@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 123 4567",
    ministries: ["Worship", "Prayer"],
    cellGroups: ["Cell A", "Cell B", "Cell C"],
    address: "123 Main St, Accra, Ghana",
    ordinationDate: "2015-06-15",
  },
  {
    id: 2,
    pastorId: "PST002",
    name: "Jane Doe",
    email: "jane.doe@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 234 5678",
    ministries: ["Evangelism", "Discipleship"],
    cellGroups: ["Cell D", "Cell E"],
    address: "456 High St, Kumasi, Ghana",
    ordinationDate: "2017-09-20",
  },
  {
    id: 3,
    pastorId: "PST003",
    name: "Mike Geller",
    email: "mike.geller@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 345 6789",
    ministries: ["Counseling", "Mens Fellowship"],
    cellGroups: ["Cell F", "Cell G"],
    address: "789 Market St, Takoradi, Ghana",
    ordinationDate: "2018-03-10",
  },
  {
    id: 4,
    pastorId: "PST004",
    name: "Jay French",
    email: "jay.french@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 456 7890",
    ministries: ["Youth", "Media"],
    cellGroups: ["Cell H", "Cell I"],
    address: "321 Beach Rd, Cape Coast, Ghana",
    ordinationDate: "2019-11-05",
  },
  {
    id: 5,
    pastorId: "PST005",
    name: "Jane Smith",
    email: "jane.smith@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 567 8901",
    ministries: ["Children", "Ushering"],
    cellGroups: ["Cell J", "Cell K"],
    address: "654 Garden Ave, Tema, Ghana",
    ordinationDate: "2016-07-22",
  },
  {
    id: 6,
    pastorId: "PST006",
    name: "Anna Santiago",
    email: "anna.santiago@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 678 9012",
    ministries: ["Hospitality", "Prayer"],
    cellGroups: ["Cell L"],
    address: "987 Hill St, Obuasi, Ghana",
    ordinationDate: "2020-01-18",
  },
  {
    id: 7,
    pastorId: "PST007",
    name: "Allen Black",
    email: "allen.black@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 789 0123",
    ministries: ["Missions", "Outreach"],
    cellGroups: ["Cell M", "Cell N"],
    address: "147 River Rd, Ho, Ghana",
    ordinationDate: "2014-12-03",
  },
  {
    id: 8,
    pastorId: "PST008",
    name: "Ophelia Castro",
    email: "ophelia.castro@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 890 1234",
    ministries: ["Womens Fellowship", "Counseling"],
    cellGroups: ["Cell O", "Cell P"],
    address: "258 Valley View, Sunyani, Ghana",
    ordinationDate: "2018-08-30",
  },
  {
    id: 9,
    pastorId: "PST009",
    name: "Derek Briggs",
    email: "derek.briggs@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 901 2345",
    ministries: ["Bible Study", "Discipleship"],
    cellGroups: ["Cell Q"],
    address: "369 Lake Rd, Koforidua, Ghana",
    ordinationDate: "2017-04-12",
  },
  {
    id: 10,
    pastorId: "PST010",
    name: "John Glover",
    email: "john.glover@floodoflife.org",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 24 012 3456",
    ministries: ["Marriage Counseling", "Mens Fellowship"],
    cellGroups: ["Cell R", "Cell S"],
    address: "741 Forest Dr, Tamale, Ghana",
    ordinationDate: "2015-10-25",
  },
];

// MEMBERS DATA (formerly STUDENTS)
export const membersData = [
  {
    id: 1,
    memberNumber: "FLE-2024-001",
    name: "John Doe",
    email: "john.doe@email.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 123 4567",
    membershipLevel: "Level 3",
    cellGroup: "Cell A",
    address: "123 Member St, Accra, Ghana",
    maritalStatus: "Married",
    occupation: "Teacher",
  },
  {
    id: 2,
    memberNumber: "FLE-2024-002",
    name: "Jane Doe",
    email: "jane.doe@email.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 234 5678",
    membershipLevel: "Level 4",
    cellGroup: "Cell B",
    address: "456 Member Ave, Kumasi, Ghana",
    maritalStatus: "Married",
    occupation: "Nurse",
  },
  {
    id: 3,
    memberNumber: "FLE-2024-003",
    name: "Mike Geller",
    email: "mike.geller@email.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 345 6789",
    membershipLevel: "Level 2",
    cellGroup: "Cell C",
    address: "789 Member Blvd, Takoradi, Ghana",
    maritalStatus: "Single",
    occupation: "Engineer",
  },
  {
    id: 4,
    memberNumber: "FLE-2024-004",
    name: "Jay French",
    email: "jay.french@email.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 456 7890",
    membershipLevel: "Level 5",
    cellGroup: "Cell D",
    address: "321 Member Rd, Cape Coast, Ghana",
    maritalStatus: "Married",
    occupation: "Business Owner",
  },
  {
    id: 5,
    memberNumber: "FLE-2024-005",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 567 8901",
    membershipLevel: "Level 3",
    cellGroup: "Cell E",
    address: "654 Member Ln, Tema, Ghana",
    maritalStatus: "Single",
    occupation: "Accountant",
  },
  {
    id: 6,
    memberNumber: "FLE-2024-006",
    name: "Anna Santiago",
    email: "anna.santiago@email.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 678 9012",
    membershipLevel: "Level 4",
    cellGroup: "Cell F",
    address: "987 Member Ct, Obuasi, Ghana",
    maritalStatus: "Married",
    occupation: "Doctor",
  },
  {
    id: 7,
    memberNumber: "FLE-2024-007",
    name: "Allen Black",
    email: "allen.black@email.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 789 0123",
    membershipLevel: "Level 2",
    cellGroup: "Cell G",
    address: "147 Member Way, Ho, Ghana",
    maritalStatus: "Single",
    occupation: "Student",
  },
  {
    id: 8,
    memberNumber: "FLE-2024-008",
    name: "Ophelia Castro",
    email: "ophelia.castro@email.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 890 1234",
    membershipLevel: "Level 5",
    cellGroup: "Cell H",
    address: "258 Member Dr, Sunyani, Ghana",
    maritalStatus: "Married",
    occupation: "Lawyer",
  },
  {
    id: 9,
    memberNumber: "FLE-2024-009",
    name: "Derek Briggs",
    email: "derek.briggs@email.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 901 2345",
    membershipLevel: "Level 3",
    cellGroup: "Cell I",
    address: "369 Member Pl, Koforidua, Ghana",
    maritalStatus: "Single",
    occupation: "Architect",
  },
  {
    id: 10,
    memberNumber: "FLE-2024-010",
    name: "John Glover",
    email: "john.glover@email.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+233 54 012 3456",
    membershipLevel: "Level 4",
    cellGroup: "Cell J",
    address: "741 Member Pkwy, Tamale, Ghana",
    maritalStatus: "Married",
    occupation: "Pastor",
  },
];

// FAMILY HEADS DATA (formerly PARENTS)
export const familyHeadsData = [
  {
    id: 1,
    name: "John Doe Sr.",
    familyMembers: ["John Doe Jr.", "Sarah Doe"],
    email: "john.doe.sr@email.com",
    phone: "+233 55 123 4567",
    address: "123 Family St, Accra, Ghana",
    familyName: "Doe Family",
  },
  {
    id: 2,
    name: "Jane Doe Sr.",
    familyMembers: ["Mike Doe", "Anna Doe"],
    email: "jane.doe.sr@email.com",
    phone: "+233 55 234 5678",
    address: "456 Family Ave, Kumasi, Ghana",
    familyName: "Doe Family",
  },
  {
    id: 3,
    name: "Mike Geller Sr.",
    familyMembers: ["Tom Geller", "Lisa Geller"],
    email: "mike.geller.sr@email.com",
    phone: "+233 55 345 6789",
    address: "789 Family Blvd, Takoradi, Ghana",
    familyName: "Geller Family",
  },
  {
    id: 4,
    name: "Jay French Sr.",
    familyMembers: ["Emma French", "James French", "Lucy French"],
    email: "jay.french.sr@email.com",
    phone: "+233 55 456 7890",
    address: "321 Family Rd, Cape Coast, Ghana",
    familyName: "French Family",
  },
  {
    id: 5,
    name: "Jane Smith Sr.",
    familyMembers: ["Peter Smith"],
    email: "jane.smith.sr@email.com",
    phone: "+233 55 567 8901",
    address: "654 Family Ln, Tema, Ghana",
    familyName: "Smith Family",
  },
  {
    id: 6,
    name: "Anna Santiago Sr.",
    familyMembers: ["Carlos Santiago", "Maria Santiago"],
    email: "anna.santiago.sr@email.com",
    phone: "+233 55 678 9012",
    address: "987 Family Ct, Obuasi, Ghana",
    familyName: "Santiago Family",
  },
  {
    id: 7,
    name: "Allen Black Sr.",
    familyMembers: ["Kevin Black", "Diana Black", "Paul Black"],
    email: "allen.black.sr@email.com",
    phone: "+233 55 789 0123",
    address: "147 Family Way, Ho, Ghana",
    familyName: "Black Family",
  },
  {
    id: 8,
    name: "Ophelia Castro Sr.",
    familyMembers: ["Sofia Castro"],
    email: "ophelia.castro.sr@email.com",
    phone: "+233 55 890 1234",
    address: "258 Family Dr, Sunyani, Ghana",
    familyName: "Castro Family",
  },
  {
    id: 9,
    name: "Derek Briggs Sr.",
    familyMembers: ["Oliver Briggs", "Chloe Briggs"],
    email: "derek.briggs.sr@email.com",
    phone: "+233 55 901 2345",
    address: "369 Family Pl, Koforidua, Ghana",
    familyName: "Briggs Family",
  },
  {
    id: 10,
    name: "John Glover Sr.",
    familyMembers: ["Samuel Glover"],
    email: "john.glover.sr@email.com",
    phone: "+233 55 012 3456",
    address: "741 Family Pkwy, Tamale, Ghana",
    familyName: "Glover Family",
  },
];

// MINISTRIES DATA (formerly SUBJECTS)
export const ministriesData = [
  {
    id: 1,
    name: "Worship Ministry",
    leaders: ["Pastor John Doe", "Pastor Jane Smith"],
  },
  {
    id: 2,
    name: "Prayer Ministry",
    leaders: ["Pastor Mike Geller", "Pastor Anna Santiago"],
  },
  {
    id: 3,
    name: "Evangelism Ministry",
    leaders: ["Pastor Jay French", "Pastor Allen Black"],
  },
  {
    id: 4,
    name: "Children's Ministry",
    leaders: ["Pastor Ophelia Castro", "Pastor Jane Doe"],
  },
  {
    id: 5,
    name: "Youth Ministry",
    leaders: ["Pastor Derek Briggs", "Pastor John Glover"],
  },
  {
    id: 6,
    name: "Media Ministry",
    leaders: ["Pastor Mike Geller", "Pastor Jay French"],
  },
  {
    id: 7,
    name: "Ushering Ministry",
    leaders: ["Pastor Jane Smith", "Pastor Anna Santiago"],
  },
  {
    id: 8,
    name: "Hospitality Ministry",
    leaders: ["Pastor Allen Black", "Pastor Ophelia Castro"],
  },
  {
    id: 9,
    name: "Counseling Ministry",
    leaders: ["Pastor John Doe", "Pastor Derek Briggs"],
  },
  {
    id: 10,
    name: "Missions Ministry",
    leaders: ["Pastor Jane Doe", "Pastor John Glover"],
  },
];

// CELL GROUPS DATA (formerly CLASSES)
export const cellGroupsData = [
  {
    id: 1,
    name: "Cell Group A",
    capacity: 20,
    level: 1,
    leader: "Pastor John Doe",
  },
  {
    id: 2,
    name: "Cell Group B",
    capacity: 22,
    level: 2,
    leader: "Pastor Jane Doe",
  },
  {
    id: 3,
    name: "Cell Group C",
    capacity: 20,
    level: 3,
    leader: "Pastor Mike Geller",
  },
  {
    id: 4,
    name: "Cell Group D",
    capacity: 18,
    level: 4,
    leader: "Pastor Jay French",
  },
  {
    id: 5,
    name: "Cell Group E",
    capacity: 16,
    level: 5,
    leader: "Pastor Jane Smith",
  },
  {
    id: 6,
    name: "Cell Group F",
    capacity: 20,
    level: 5,
    leader: "Pastor Anna Santiago",
  },
  {
    id: 7,
    name: "Cell Group G",
    capacity: 18,
    level: 2,
    leader: "Pastor Allen Black",
  },
  {
    id: 8,
    name: "Cell Group H",
    capacity: 22,
    level: 3,
    leader: "Pastor Ophelia Castro",
  },
  {
    id: 9,
    name: "Cell Group I",
    capacity: 18,
    level: 4,
    leader: "Pastor Derek Briggs",
  },
  {
    id: 10,
    name: "Cell Group J",
    capacity: 20,
    level: 1,
    leader: "Pastor John Glover",
  },
];

// SERVICES DATA (formerly LESSONS)
export const servicesData = [
  {
    id: 1,
    ministry: "Worship Ministry",
    cellGroup: "Cell Group A",
    pastor: "Pastor John Doe",
  },
  {
    id: 2,
    ministry: "Prayer Ministry",
    cellGroup: "Cell Group B",
    pastor: "Pastor Jane Doe",
  },
  {
    id: 3,
    ministry: "Evangelism Ministry",
    cellGroup: "Cell Group C",
    pastor: "Pastor Mike Geller",
  },
  {
    id: 4,
    ministry: "Children's Ministry",
    cellGroup: "Cell Group D",
    pastor: "Pastor Jay French",
  },
  {
    id: 5,
    ministry: "Youth Ministry",
    cellGroup: "Cell Group E",
    pastor: "Pastor Jane Smith",
  },
  {
    id: 6,
    ministry: "Media Ministry",
    cellGroup: "Cell Group F",
    pastor: "Pastor Anna Santiago",
  },
  {
    id: 7,
    ministry: "Ushering Ministry",
    cellGroup: "Cell Group G",
    pastor: "Pastor Allen Black",
  },
  {
    id: 8,
    ministry: "Hospitality Ministry",
    cellGroup: "Cell Group H",
    pastor: "Pastor Ophelia Castro",
  },
  {
    id: 9,
    ministry: "Counseling Ministry",
    cellGroup: "Cell Group I",
    pastor: "Pastor Derek Briggs",
  },
  {
    id: 10,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group J",
    pastor: "Pastor John Glover",
  },
];

// SOUL WINNING TARGETS DATA (formerly EXAMS)
export const soulWinningTargetsData = [
  {
    id: 1,
    ministry: "Evangelism Ministry",
    cellGroup: "Cell Group A",
    leader: "Pastor John Doe",
    date: "2025-03-01",
    target: 10,
  },
  {
    id: 2,
    ministry: "Outreach Ministry",
    cellGroup: "Cell Group B",
    leader: "Pastor Jane Doe",
    date: "2025-03-15",
    target: 15,
  },
  {
    id: 3,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group C",
    leader: "Pastor Mike Geller",
    date: "2025-03-20",
    target: 20,
  },
  {
    id: 4,
    ministry: "Youth Ministry",
    cellGroup: "Cell Group D",
    leader: "Pastor Jay French",
    date: "2025-03-25",
    target: 12,
  },
  {
    id: 5,
    ministry: "Children's Ministry",
    cellGroup: "Cell Group E",
    leader: "Pastor Jane Smith",
    date: "2025-04-01",
    target: 8,
  },
  {
    id: 6,
    ministry: "Prayer Ministry",
    cellGroup: "Cell Group F",
    leader: "Pastor Anna Santiago",
    date: "2025-04-05",
    target: 10,
  },
  {
    id: 7,
    ministry: "Evangelism Ministry",
    cellGroup: "Cell Group G",
    leader: "Pastor Allen Black",
    date: "2025-04-10",
    target: 15,
  },
  {
    id: 8,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group H",
    leader: "Pastor Ophelia Castro",
    date: "2025-04-15",
    target: 25,
  },
  {
    id: 9,
    ministry: "Outreach Ministry",
    cellGroup: "Cell Group I",
    leader: "Pastor Derek Briggs",
    date: "2025-04-20",
    target: 12,
  },
  {
    id: 10,
    ministry: "Youth Ministry",
    cellGroup: "Cell Group J",
    leader: "Pastor John Glover",
    date: "2025-04-25",
    target: 18,
  },
];

// OUTREACH PROGRAMS DATA (formerly ASSIGNMENTS)
export const outreachProgramsData = [
  {
    id: 1,
    ministry: "Evangelism Ministry",
    cellGroup: "Cell Group A",
    leader: "Pastor John Doe",
    dueDate: "2025-03-10",
    location: "Accra Mall",
  },
  {
    id: 2,
    ministry: "Outreach Ministry",
    cellGroup: "Cell Group B",
    leader: "Pastor Jane Doe",
    dueDate: "2025-03-20",
    location: "Kumasi Market",
  },
  {
    id: 3,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group C",
    leader: "Pastor Mike Geller",
    dueDate: "2025-03-25",
    location: "Takoradi Harbor",
  },
  {
    id: 4,
    ministry: "Children's Ministry",
    cellGroup: "Cell Group D",
    leader: "Pastor Jay French",
    dueDate: "2025-03-30",
    location: "Cape Coast School",
  },
  {
    id: 5,
    ministry: "Youth Ministry",
    cellGroup: "Cell Group E",
    leader: "Pastor Jane Smith",
    dueDate: "2025-04-05",
    location: "Tema Community Center",
  },
  {
    id: 6,
    ministry: "Media Ministry",
    cellGroup: "Cell Group F",
    leader: "Pastor Anna Santiago",
    dueDate: "2025-04-10",
    location: "Online Broadcast",
  },
  {
    id: 7,
    ministry: "Hospitality Ministry",
    cellGroup: "Cell Group G",
    leader: "Pastor Allen Black",
    dueDate: "2025-04-15",
    location: "Church Fellowship Hall",
  },
  {
    id: 8,
    ministry: "Counseling Ministry",
    cellGroup: "Cell Group H",
    leader: "Pastor Ophelia Castro",
    dueDate: "2025-04-20",
    location: "Church Counseling Center",
  },
  {
    id: 9,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group I",
    leader: "Pastor Derek Briggs",
    dueDate: "2025-04-25",
    location: "Northern Region",
  },
  {
    id: 10,
    ministry: "Evangelism Ministry",
    cellGroup: "Cell Group J",
    leader: "Pastor John Glover",
    dueDate: "2025-04-30",
    location: "Tamale Central",
  },
];

// SOULS WON RECORDS DATA (formerly RESULTS)
export const soulsWonData = [
  {
    id: 1,
    ministry: "Evangelism Ministry",
    cellGroup: "Cell Group A",
    leader: "Pastor John Doe",
    member: "John Doe",
    date: "2025-02-15",
    type: "soul winning",
    count: 5,
  },
  {
    id: 2,
    ministry: "Outreach Ministry",
    cellGroup: "Cell Group B",
    leader: "Pastor Jane Doe",
    member: "Jane Doe",
    date: "2025-02-16",
    type: "outreach",
    count: 8,
  },
  {
    id: 3,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group C",
    leader: "Pastor Mike Geller",
    member: "Mike Geller",
    date: "2025-02-17",
    type: "soul winning",
    count: 3,
  },
  {
    id: 4,
    ministry: "Youth Ministry",
    cellGroup: "Cell Group D",
    leader: "Pastor Jay French",
    member: "Jay French",
    date: "2025-02-18",
    type: "outreach",
    count: 6,
  },
  {
    id: 5,
    ministry: "Children's Ministry",
    cellGroup: "Cell Group E",
    leader: "Pastor Jane Smith",
    member: "Jane Smith",
    date: "2025-02-19",
    type: "soul winning",
    count: 4,
  },
  {
    id: 6,
    ministry: "Prayer Ministry",
    cellGroup: "Cell Group F",
    leader: "Pastor Anna Santiago",
    member: "Anna Santiago",
    date: "2025-02-20",
    type: "soul winning",
    count: 7,
  },
  {
    id: 7,
    ministry: "Media Ministry",
    cellGroup: "Cell Group G",
    leader: "Pastor Allen Black",
    member: "Allen Black",
    date: "2025-02-21",
    type: "outreach",
    count: 5,
  },
  {
    id: 8,
    ministry: "Hospitality Ministry",
    cellGroup: "Cell Group H",
    leader: "Pastor Ophelia Castro",
    member: "Ophelia Castro",
    date: "2025-02-22",
    type: "soul winning",
    count: 3,
  },
  {
    id: 9,
    ministry: "Counseling Ministry",
    cellGroup: "Cell Group I",
    leader: "Pastor Derek Briggs",
    member: "Derek Briggs",
    date: "2025-02-23",
    type: "outreach",
    count: 4,
  },
  {
    id: 10,
    ministry: "Missions Ministry",
    cellGroup: "Cell Group J",
    leader: "Pastor John Glover",
    member: "John Glover",
    date: "2025-02-24",
    type: "soul winning",
    count: 6,
  },
];

// CHURCH EVENTS DATA (formerly EVENTS)
export const churchEventsData = [
  {
    id: 1,
    title: "Sunday Service",
    cellGroup: "All Cell Groups",
    date: "2025-03-02",
    startTime: "09:00",
    endTime: "11:00",
    location: "Main Sanctuary",
  },
  {
    id: 2,
    title: "Bible Study",
    cellGroup: "Cell Group A",
    date: "2025-03-05",
    startTime: "18:00",
    endTime: "19:30",
    location: "Fellowship Hall",
  },
  {
    id: 3,
    title: "Prayer Meeting",
    cellGroup: "All Cell Groups",
    date: "2025-03-07",
    startTime: "18:00",
    endTime: "20:00",
    location: "Prayer Room",
  },
  {
    id: 4,
    title: "Youth Night",
    cellGroup: "Cell Group D",
    date: "2025-03-08",
    startTime: "17:00",
    endTime: "20:00",
    location: "Youth Center",
  },
  {
    id: 5,
    title: "Children's Service",
    cellGroup: "Cell Group E",
    date: "2025-03-09",
    startTime: "10:00",
    endTime: "12:00",
    location: "Children's Church",
  },
  {
    id: 6,
    title: "Missions Conference",
    cellGroup: "All Cell Groups",
    date: "2025-03-14",
    startTime: "09:00",
    endTime: "16:00",
    location: "Main Sanctuary",
  },
  {
    id: 7,
    title: "Men's Fellowship",
    cellGroup: "Cell Group G",
    date: "2025-03-15",
    startTime: "08:00",
    endTime: "10:00",
    location: "Fellowship Hall",
  },
  {
    id: 8,
    title: "Women's Fellowship",
    cellGroup: "Cell Group H",
    date: "2025-03-15",
    startTime: "10:30",
    endTime: "12:30",
    location: "Fellowship Hall",
  },
  {
    id: 9,
    title: "Marriage Seminar",
    cellGroup: "Cell Group I",
    date: "2025-03-16",
    startTime: "14:00",
    endTime: "17:00",
    location: "Conference Room",
  },
  {
    id: 10,
    title: "Evangelism Outreach",
    cellGroup: "All Cell Groups",
    date: "2025-03-22",
    startTime: "09:00",
    endTime: "15:00",
    location: "City Center",
  },
];

// CHURCH ANNOUNCEMENTS DATA (formerly ANNOUNCEMENTS)
export const churchAnnouncementsData = [
  {
    id: 1,
    title: "Special Prayer Request",
    cellGroup: "All Cell Groups",
    date: "2025-02-28",
    priority: "High",
  },
  {
    id: 2,
    title: "Leadership Meeting",
    cellGroup: "Cell Group A",
    date: "2025-02-28",
    priority: "Normal",
  },
  {
    id: 3,
    title: "Baptism Service",
    cellGroup: "All Cell Groups",
    date: "2025-03-01",
    priority: "High",
  },
  {
    id: 4,
    title: "Ministry Fair",
    cellGroup: "All Cell Groups",
    date: "2025-03-02",
    priority: "Normal",
  },
  {
    id: 5,
    title: "Choir Practice",
    cellGroup: "Cell Group C",
    date: "2025-03-02",
    priority: "Low",
  },
  {
    id: 6,
    title: "Church Cleaning",
    cellGroup: "Cell Group F",
    date: "2025-03-03",
    priority: "Normal",
  },
  {
    id: 7,
    title: "New Member Class",
    cellGroup: "All Cell Groups",
    date: "2025-03-04",
    priority: "High",
  },
  {
    id: 8,
    title: "Food Drive",
    cellGroup: "Cell Group H",
    date: "2025-03-05",
    priority: "Normal",
  },
  {
    id: 9,
    title: "Pastor's Anniversary",
    cellGroup: "All Cell Groups",
    date: "2025-03-06",
    priority: "High",
  },
  {
    id: 10,
    title: "Blood Donation",
    cellGroup: "Cell Group J",
    date: "2025-03-07",
    priority: "Normal",
  },
];

// CHURCH CALENDAR EVENTS
export const churchCalendarEvents = [
  {
    title: "Sunday Service",
    allDay: false,
    start: new Date(2025, 2, 2, 9, 0),
    end: new Date(2025, 2, 2, 11, 0),
  },
  {
    title: "Bible Study",
    allDay: false,
    start: new Date(2025, 2, 3, 18, 0),
    end: new Date(2025, 2, 3, 19, 30),
  },
  {
    title: "Prayer Meeting",
    allDay: false,
    start: new Date(2025, 2, 4, 18, 0),
    end: new Date(2025, 2, 4, 20, 0),
  },
  {
    title: "Youth Service",
    allDay: false,
    start: new Date(2025, 2, 5, 17, 0),
    end: new Date(2025, 2, 5, 19, 0),
  },
  {
    title: "Choir Practice",
    allDay: false,
    start: new Date(2025, 2, 6, 18, 0),
